### ISSUE TITLE
Add a userspace networking mode for the agent

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#187]
Running the `apex` agent today requires root access, or at least `CAP_NET_ADMIN` capabilities to be able to set up a wireguard network interface. This limits `apex` from being used in many container-based environments where this permissions level is not normally available.

To make `apex` the most useful in those environments, the agent needs a way to provide connectivity into an Apex Zone using only userspace networking.

As some inspiration, Tailscale supports a mode like this: https://tailscale.com/kb/1112/userspace-networking/

**Comment by dave-tucker** [comment]
Soft blocked on #168

**Comment by nerdalert** [comment]
### userspace wireguard-go 
I dug into this a bit, we already run the user space `wireguard-go` for Darwin, it's basically the same for Linux. Create the dev with wireguard-go and then everything else is the same, e.g. using the `wg` binary to configure and read from the interface.

Since it's using `/dev/net/tun` it still requires privileges. Here is an example:

```
# Create the user space interface:
sudo ./wireguard-go wg0
$ sudo wg show

interface: wg0
  listening port: 59502

# Configure the userspace interface with the normal wg binary
sudo wg set wg0 listen-port 12345 private-key /etc/wireguard/private.key

$ sudo wg show
interface: wg0
  public key: VchcCdEgTREfX9CzTgmjdvUdeDQ6xv/wmaftA4TQdXs=
  private key: (hidden)
  listening port: 12345

# Killing the wireguard-go process destroys the interface (as you may have noticed in our OSX implementation)
```

It would only be a few lines of code to add a `--userspace` option for Linux but it's probably not nessecary until we know what the use case is. One would be the same implementation across platforms but there are even some disclaimers around Linux and WIndows on the [wireguard-go](https://github.com/WireGuard/wireguard-go) project site I remember seeing when doing the windows implementation.

If anyone wants to kick the tires on it in a container here is a quick paste to get you going, tldr, I dont see anyway around cap net admin.


```
### Note: this will complain about prvieldges. To get it working add net --cap-add=NET_ADMIN
docker run -itd  -v /dev/net/tun:/dev/net/tun --name wg-go  ubuntu
docker exec -i -t $(docker ps -l -q) /bin/bash

# Inside the container
apt-get update 
apt-get install -y wget git make 

# Build
wget https://go.dev/dl/go1.19.3.linux-amd64.tar.gz
rm -rf /usr/local/go 
tar -C /usr/local -xzf go1.19.3.linux-amd64.tar.gz
rm -rf /usr/local/go &&  tar -C /usr/local -xzf go1.19.3.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
git clone https://github.com/WireGuard/wireguard-go.git
cd wireguard-go
make

# Run
./wireguard-go
``` 

### connecting external non-wg devices

- A fallback to QUIC for devices that don't support Wireguard leveraging MASQUE. Good blog from CF on it [Unlocking QUIC’s proxying potential with MASQUE](https://blog.cloudflare.com/unlocking-quic-proxying-potential/)
- SOCKS5 gives some auth to an open port for web proxying into a wg zone. Kind of limited on the use cases though (unless I'm missing something).
- Plenty more creative ways to get traffic in or even tunnel WG over TLS out there. 
- None of those address a scenario like a printer or some IOT device/sensor that doesn't expose an OS. At that point you are pretty limited to a forwarding interface on the spoke node that is allowing forwarding based on an explicit trust of the src address in a IPTables forwarding rule into the WG zone. This is just basically acting as a router in a remote office, so while there is zero auth it is basically how the majority of enterprise networks operate today.
