### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by russellb** [nexodus-io/nexodus#637]
### Describe the Problem Statement

Nexodus currently only supports IPv4. 

### Describe the Enhancement

IPv6 (single-stack and dual-stack) should be added across the whole system. Design work is needed to define what we want IPv6 support to look like in more detail.

**Comment by nerdalert** [comment]
### Overview:
This is to support v6 addressing in both the api-server and wireguard driver. By default, every driver, current and future should get a v6 interface along with a v4 address (example wg0). The initial work will encapsulate v6 over v4. IPv6 as a tunnel endpoint for v4 encapped transport can be future work.

### Add support for v6 Tasks ###

- **Server changes:**
- [ ] Database migration for v6 fields
- [ ] Add v6 fields in Org and Device models
- [ ] Add v6 support in IPAM (both leasing and deleting)

- **Agent changes:**
- [ ] Add checks for v6 support in Linux, if v6 is not supported. Primarily for containers since runtimes like Docker disable v6 by default.
- [ ] Checks on unsupported v6 options `--request-ip` & `--child-prefix`
- [ ] Add interface and route support for OSX
- [ ] Add interface and route support for Linux
- [ ] Add interface and route support for Windoze
- [ ] Add relay node support for the supernet prefix for regular spoke nodes to reach relay-only nodes
- [ ] ip6tables support for relay

- **e2e:**

- [ ] Add v6 support to the test containers (probably sysctl options passed to enable v6)
- [ ] Enable v6 in current v4 tests of applicable features

- **Misc:**

- [ ] Doc updates
- [ ] Nexctl v6 field support in Org and Device models

Not included (most can be future issues):
Since this is fairly wide reaching and doesn't lend itself to being done over time in smaller chunks:
- support for `--child-prefixv6` in a followup. 
- `--request-ip` is one that I could go either way on supporting. 
- IPv6 snowflake addresses should probably be handled with our DNS implementation in the future rather than static v6 addresses (also keeps the flag count down in nexd.
- v6 TEP support. That should be done separately as it also introduces a new round of testing required.
- v6 support in keepalives.

**Comment by russellb** [comment]
@nerdalert could you write this up in the form of a `docs/development/design` doc? I would expect it to cover:

- overview of the added/changed functionality
- API changes proposed
- CLI interface changes proposed
- other changes to the user experience

**Comment by russellb** [comment]
@nerdalert could you write this up in the form of a `docs/development/design` doc? I would expect it to cover:

- overview of the added/changed functionality
- API changes proposed
- CLI interface changes proposed
- other changes to the user experience

**Comment by russellb** [comment]
@nerdalert could you update this with current status, create issues for what's missing, and close this out?

**Comment by russellb** [comment]
closing this out since the first pass was merged. Please file follow-up issues for specific items that need work.
