### ISSUE TITLE
Restarting `nexd` on a device pushes API updates to all peers

### ISSUE THREAD

**Issue by chirino** [nexodus-io/nexodus#958]
### Describe the bug

Restarting `nexd` on device pushes API updates to all peers.  Not exactly a bug, since it does not cause a functional error, it does create unnecessary work for all the peers in the org since the data for the device should not have changed between restarts.

### How to Reproduce

1. Start nexd on device A and B.  
2. Monitor the logs of device B.  
3. Restart nexd on device A
4. Notice that in the logs of device B it get a peer device update.

### Expected Behavior

Step 4. should not occur.  Since the peer has already been configured and it's settings should not have changed.

**Comment by russellb** [comment]
Sounds like a change is needed in two places

1. nexd shouldn’t be sending an update api call if nothing has changed. 
2. The api server shouldn’t be broadcasting an update to all clients if an update request came in that didn’t actually change anything.

**Comment by russellb** [comment]
I just looked at this again. It still happens, but I don't think it's a bug. When the device restarts, its endpoints change because it's using a new local port each time.

I think nexd should be reusing the same port, though. As it is now, every device in the whole mesh has to change its configuration for a device every time it restarts because of this.

**Comment by russellb** [comment]
I updated the priority on this one to "Critical" because it means we're interrupting the data plane on every `nexd` restart. Traffic will be interrupted until peering is re-established. Best case everything is resolved within a few seconds, worst case it could take minutes (at least based on our current implementation).

The impact of this on a relay node could be even more significant because of how many devices are impacted by the traffic interruption there.
